### ISSUE TITLE
Keyboard shortcut does not work

### ISSUE THREAD

**Issue by psyphre** [Risu/Tiled-Quicklaunch#2]
Love this applet - one of my favs.

Unfortunately the keyboard shortcut does not seem to work. When I set a shortcut and apply, then reopen the settings that shortcut has dissapeared. Using version 3.3.

Let me know what other info you need. Thanks!

Edit: Adding system information:

KDE Plasma 5.19.5
KDE Frameworks: 5.74.0
QT Version 5.14.2

**Comment by Risu** [comment]
Please provide information about your system, plasma version, framework version and qt version.
I cannot reproduce this problem on the KDE Neon User Edition.

**Comment by psyphre** [comment]
Ok sure, have updated the original post with that information. thanks.

**Comment by Risu** [comment]
I've tested Kubuntu 20.10 with the same plasma version as yours and keyboard shortcuts are remembered. Maybe you are using the key which is somehow not allowed in plasma?

**Comment by psyphre** [comment]
Ah, actually i can see what is going on now. The tiled menu that comes up when I click on the mouse is not the same as the tiled menu that comes up when I press the keyboard shortcut. A restart seemed to have fixed the shortcut key not sticking.

The mouse click brings up a menu where I have added tiles to.
The keyboard shortcut brings up a blank menu - as if I just added the widget and nothing has yet been added.

I have tried removing the applet and re-adding incase that instance was bugged.

**Comment by Risu** [comment]
That is different issue for new topic.
Quick fix:
Insert into risu.tiled.quicklaunch/contents/ui/Main.qml in line 77:

```
onExpandedChanged: {
	if (expanded && !popup.visible) {
        plasmoid.expanded = false
        popup.visible = true
    }
}
```

Plasmoids are located in /home/USERNAME/.local/share/plasma/plasmoids.
Then restart plasma or system.

**Comment by psyphre** [comment]
Thanks for the quick responses. I will close this one down and raise a new bug which is specific to this issue,
