### ISSUE TITLE
Keyboard shortcut and mouse bring up different menus

### ISSUE THREAD

**Issue by psyphre** [Risu/Tiled-Quicklaunch#3]
The tiled menu that comes up when I click on the mouse is not the same as the tiled menu that comes up when I press the keyboard shortcut. A restart seemed to have fixed the shortcut key not sticking.

The mouse click brings up a menu where I have added tiles to.
The keyboard shortcut brings up a blank menu - as if I just added the widget and nothing has yet been added.

I have tried removing the applet and re-adding incase that instance was bugged.

**Comment by psyphre** [comment]
I have tried the below fix, what it seems to do is bring up both menus, which does not quite solve the problem.

-------------------------------------------------------------------------------------------------------------
Quick fix:
Insert into risu.tiled.quicklaunch/contents/ui/Main.qml in line 77:

onExpandedChanged: {
	if (expanded && !popup.visible) {
        plasmoid.expanded = false
        popup.visible = true
    }
}
Plasmoids are located in /home/USERNAME/.local/share/plasma/plasmoids.
Then restart plasma or system.

**Comment by Risu** [comment]
To solve this in quick way:
In Main.qml remove:
```
	PlasmaCore.Dialog {
        id: popup
        type: PlasmaCore.Dialog.PopupMenu
        flags: Qt.WindowStaysOnTopHint
        hideOnWindowDeactivate: true
        location: plasmoid.location
        visualParent: plasmoid
        
        mainItem: Popup { } 
    }
```
insert:
```
    Popup { 
         id: popup
    } 
```

In LauncherIcon.qml:
Remove:
```
	onClicked: {
		popup.visible = !popup.visible
	}
```
Insert:
```
	onClicked: {
		plasmoid.expanded = !plasmoid.expanded 
	}
```

The "quick fix" replace with:
```
onExpandedChanged: {
    if (expanded) popup.visible = true
}
```

This will solve all keyboard shortcut related issues.
Probably In code all width and height related things needs to be adjusted to these changes too.

**Comment by Risu** [comment]
New idea for "quick fix" only:
```
    onExpandedChanged: {
        popup.visible = !popup.visible
    }
    Plasmoid.fullRepresentation: PlasmaCore.Dialog {
        visible: false
    }
```
Commited to repository waiting for your testing.

**Comment by psyphre** [comment]
This worked like a charm!! Great stuff thank you.

    onExpandedChanged: {
        popup.visible = !popup.visible
    }
    Plasmoid.fullRepresentation: PlasmaCore.Dialog {
        visible: false
    }
