### ISSUE TITLE
Change panel's icon size

### ISSUE THREAD

**Issue by servitecbaires** [Risu/Tiled-Quicklaunch#5]
Hi again!
My name is Martin.
I have this issue using the widget in the plasma panel: The icon size is microscopical. I mean about 6x6 pixels approx.
Is that OK? I'm trying to use it like my main app launcher, because it is the most customizable (or the only one).
But its very hard to reach it if the icon so little.

Thanks again! your work is awesome.

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.8.0-55-generic

**Comment by Risu** [comment]
The idea is that it should be small to take the least space on the taskbar, but you can select any icon in configuration applet.  You can scale the icon in any graphical editor and save it on the drive. Then select it in Panel Icon from General tab in the settings.

**Comment by Risu** [comment]
Can you post screenshot how it looks on your system?

**Comment by servitecbaires** [comment]
I realized that unchecking the "Fixed Size" box and RESTARTING THE PLASMA SESSION (I didn't do it testing this "issue") the icon takes it's full size.

Sorry for wasting your time!
And thanks again for your work.
Martin
